import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#000000",
        secondary: "#ffffff",
        accent: "#1FB2A5",
        neutral: "#191D24",
        "base-100": "#2A303C",
        info: "#3ABFF8",
        success: "#36D399",
        warning: "#FBBD23",
        error: "#F87272",
      },
      screens: {
        xs: "200px",
        sxs: "331px",
        "1sxs": "351px",
        "2sxs": "371px",
        mxs: "401px",
        lxs: "451px",
        "1xs": "481px",
        "2xs": "501px",
        "3xs": "551px",
        sm: "601px",
        xsm: "651px",
        "2sm": "701px",
        md: "768px",
        "2md": "801px",
        "3md": "901px",
        "1lg": "951px",
        mlg: "1001px",
        "2mlg": "1011px",
        lg: "1024px",
        "2lg": "1101px",
        "3lg": "1151px",
        "1xl": "1201px",
        "1mxl": "1251px",
        xl: "1280px",
        xxl: "1330px",
        "2xl": "1450px",
      },
    },
  },
  plugins: [require("daisyui")],
  daisyui: {
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: true,
    themeRoot: ":root",
    important: true,
  },
};
export default config;
