import { FcBusinessman } from "react-icons/fc";
import type { GenderMenuProps, NavigationMenuProps } from "./types";
import { FcBusinesswoman } from "react-icons/fc";

export const NAVIGATION_MENU: NavigationMenuProps[] = [
  {
    menuTitle: "Home",
    pathname: "/",
  },
  {
    menuTitle: "Features",
    pathname: "/features",
  },
  {
    menuTitle: "About",
    pathname: "/about",
  },
  {
    menuTitle: "Success Stories",
    pathname: "/success-stories",
  },
  {
    menuTitle: "Contact",
    pathname: "/contact",
  },
];

export const GENDER_OPT: GenderMenuProps[] = [
  {
    value: "man",
    label: "Man",
    icon: FcBusinessman,
  },
  {
    value: "woman",
    label: "Woman",
    icon: FcBusinesswoman,
  },
];

export const PREFFERED_GENDER_OPT: GenderMenuProps[] = [
  {
    value: "man",
    label: "Man",
    icon: FcBusinessman,
  },
  {
    value: "woman",
    label: "Woman",
    icon: FcBusinesswoman,
  },
];
export const DUMMY_GIRLS_DATA = [
  {
    name: "Jane Claudia Claudia",
    age: 19,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman1.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "online",
  },
  {
    name: "Jean",
    age: 20,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman2.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "online",
  },
  {
    name: "Jane Claudia Claudia",
    age: 19,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman1.jpg",
    bio: "Lorem Ipsum ",
    status: "offine",
  },
  {
    name: "Jean",
    age: 20,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman2.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "online",
  },
  {
    name: "Jane Claudia Claudia",
    age: 19,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman1.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "offine",
  },
  {
    name: "Jean",
    age: 20,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman2.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing  industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "online",
  },
  {
    name: "Jane Claudia Claudia",
    age: 19,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman1.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "offine",
  },
  {
    name: "Jean",
    age: 20,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman2.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing  industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "online",
  },
  {
    name: "Jane Claudia Claudia",
    age: 19,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman1.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "offine",
  },
  {
    name: "Jean",
    age: 20,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman2.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing  industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "online",
  },
  {
    name: "Jane Claudia Claudia",
    age: 19,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman1.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "offine",
  },
  {
    name: "Jean",
    age: 20,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman2.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing  industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "online",
  },
  {
    name: "Jane Claudia Claudia",
    age: 19,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman1.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "offine",
  },
  {
    name: "Jean",
    age: 20,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman2.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing  industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "online",
  },
  {
    name: "Jane Claudia Claudia",
    age: 19,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman1.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "offine",
  },
  {
    name: "Jean",
    age: 20,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman2.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing  industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "online",
  },
  {
    name: "Jane Claudia Claudia",
    age: 19,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman1.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "offine",
  },
  {
    name: "Jean",
    age: 20,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman2.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing  industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "online",
  },
  {
    name: "Jane Claudia Claudia",
    age: 19,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman1.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "offine",
  },
  {
    name: "Jean",
    age: 20,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman2.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing  industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "online",
  },
  {
    name: "Jane Claudia Claudia",
    age: 19,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman1.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "offine",
  },
  {
    name: "Jean",
    age: 20,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman2.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing  industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "online",
  },
  {
    name: "Jane Claudia Claudia",
    age: 19,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman1.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "offine",
  },
  {
    name: "Jean",
    age: 20,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman2.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing  industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "online",
  },
  {
    name: "Jane Claudia Claudia",
    age: 19,
    hometown: "Bohol,PH",
    gender: "female",
    image: "/images/woman/woman1.jpg",
    bio: "Lorem Ipsum is simply dummy text of the printing industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. ",
    status: "offine",
  },
];
